server:
  servlet:
    context-path: /api
spring:
  application:
    name: go_linguage_server
  datasource:
    url: jdbc:postgresql://localhost:5432/golinguage
    username: postgres
    password: Sohappy212
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 662065393473-e40laortuec76203hspjr7slaeh7uj47.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/auth/google
            scope:
              - email
              - profile
jwt:
  secret-key: 78040db429b610814e9f299ef8590b28be75aeacd9ff1f3e53bc8b72f4c0c88c
google:
  client-id: 662065393473-e40laortuec76203hspjr7slaeh7uj47.apps.googleusercontent.com
  client-secret: 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
stripe:
  secret-key: sk_test_51QzNZxIYP7o7tjuBqKpSvwYVj4ZLzxFs6Wi3RXfpgHL4aP6jFYBdAi643uxz5w93gfqFGoGkHd5yO8prJvTxfKUz00ISpeg7Qv
  web-hook-key: whsec_d5ea053ef8e234a74dfcd59f8bedaa2bd276d301fee2c2866023a3d08adc759d
